### PR TITLE
Merge development branch into main branch

### PR DESCRIPTION
**Pull request by AkshithaReddy1899**
# This PR is created to merge development branch into main branch

**NOTE : Due to some issues me and my partner were unpaired and I had to finish the project by myself and student success approved of this**

## video link 

[Loom video link](https://www.loom.com/share/06603b25cbec4f6caf5cf04932846966)

#  Things to do 

- Use JavaScript to make websites dynamic and build basic single page apps.
- Use ES6 syntax.
- Use ES6 modules.
- Use callbacks and promises.
- Use webpack.
- Apply JavaScript best practices and language style guides in code.
- Use AAA pattern for unit tests.
- Write units tests for a JavaScript app.
- Follow Gitflow.
- Solve simple git conflicts.
- Send and receive data from an API.
- Use API documentation.
- Understand and use JSON.
- Make JavaScript code synchronous.

### CODE REVIEW

**Review by ReshyResh — CHANGES_REQUESTED** [review]
# Hi team, 

### You did an amazing job with this capstone project so far!
  - ✔ Pleasant UX with nice animations.
  - ✔ Correct implementation of the API to read/write data.
  - ✔ Tests are all passing.
  - ✔ Following correct Gitflow.

#### There are some small issues that you still need to work on to go to the next project but the project is almost complete!


## Required Changes ♻️

- [ ] You did an amazing presentation for your project, @AkshithaReddy1899 , but, as per requirement, I must request you to record it again so @OybekKayumov  can contribute as well. You're both supposed to show up in the presentation and talk about the project, please.
- [ ] I suggest you add some validation to the comments form. I tried typing some very long strings and the comment would be posted as usual. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] It would be nice if you included both authors in the readme file.


Cheers and Happy coding! 👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AkshithaReddy1899** [comment]
Hi @ReshyResh 

As mentioned in the PR description. Oybek and me are not partners. I finished the whole thing by myself. Should I still include him in the video when he has not contributed in anyway??

**Comment by ReshyResh** [comment]
I saw that the commits ratio was pretty even for the most part and he even made some commits today, so I thought he was part of the team, but if that's not the case then I apologize, you can keep the current video, it is more than enough!

**Review by uwadonat — APPROVED** [review]
Hi **@[AkshithaReddy1899](https://github.com/AkshithaReddy1899),** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
